### PR TITLE
add docker image & CI

### PR DESCRIPTION
**Pull request by xxchan**

### CODE REVIEW

**Comment by Endle** [comment]
Thank you so much for your PR! It looks good to me.

Before merging it to master branch, could you please do a few trivial changes?

1. Could you please have a look on https://deepsource.io/gh/Endle/fireSeqSearch/run/47b09457-8a30-46cc-ba35-41c891da5174/rust/RS-W1031?listindex=0  If you have a strong reason to ignore this warning, could you please add a comment for it?
2. In the README file, could you mark the Docker method as experimental? I'll remove this tag later when the Docker release works good
3. Could you please add a quick note in README about how to use the Docker image without docker-compose? Besides, I'm a bit in doubt that if `docker-compose` could benefit fireseqsearch a lot, but I'll accept your proposal for adding a `docker-compose.yml` file


Thank you again for your contrib. Happy New Year!

**Comment by xxchan** [comment]
@Endle comments resolved & Happy New Year!

**Comment by xxchan** [comment]
Hmmmm DeepSource is even more pedantic than clippy...

**Comment by Endle** [comment]
Thank you for your work.

I'm sorry that I'm asking for one more change: Could you please revert to https://github.com/Endle/fireSeqSearch/pull/101/commits/31ef8cd5b52dd6f894498e262e9269178241680d ?

I'm very grateful for the style fix, but I prefer to split the style fix and the actual commit in different PRs to reduce review work, and make the git history clean.

**Pull request merged**
